spring.application.name=Spring-AI
spring.ai.openai.api-key=${OPENAI_API_KEY}

#spring.datasource.url=jdbc:postgresql://localhost:5432/pg_vector_db
#spring.datasource.username=postgres
#spring.datasource.password=password
#
#spring.jpa.show-sql=true
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.main.allow-bean-definition-overriding=true
#
#spring.sql.init.schema-locations=classpath:init/schema.sql
#spring.sql.init.mode=always


#docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.ai.vectorstore.redis.index-name=product-index
spring.ai.vectorstore.redis.prefix=product